-- DROP TABLE IF EXISTS icc_credito;
CREATE TABLE icc_credito(
  icc_credito character varying(255) NOT NULL DEFAULT gen_random_uuid(),
  legacy_cartera_id numeric(10, 0) NOT NULL,
  c_period_id numeric(10, 0),
  cantidad_cuotas int,
  cantidad_prorrogas int,
  comision_acumulada_por_cobrar numeric,
  cuotas_vencidas int,
  dias_mora_interes int,
  dias_mora_principal int,
  fecha_otorgamiento timestamp without time zone,
  fecha_vencimiento_credito timestamp without time zone,
  id_clasificacion_credito int,
  id_tipo_credito int,
  id_credito int,
  id_credito_anterior int,
  id_destino_credito int,
  id_garantia int,
  id_linea int,
  id_modalidad_credito int,
  id_moneda int,
  id_municipio int,
  id_oficina int,
  id_origen_recursos int,
  id_periodo_cobro_interes int,
  id_periodo_cobro_principal int,
  id_sindicado int,
  id_situacion_credito int,
  id_tipo_agrupacion_credito int,
  interes_corriente numeric,
  interes_vencidos numeric,
  mto_adjudicacion_credito numeric,
  mto_intereses_por_vencer_030 numeric,
  mto_intereses_por_vencer_060 numeric,
  mto_intereses_por_vencer_090 numeric,
  mto_intereses_por_vencer_120 numeric,
  mto_intereses_por_vencer_180 numeric,
  mto_intereses_por_vencer_360 numeric,
  mto_intereses_por_vencer_mas_360 numeric,
  mto_original numeric,
  mto_por_vencer_030 numeric,
  mto_por_vencer_060 numeric,
  mto_por_vencer_090 numeric,
  mto_por_vencer_120 numeric,
  mto_por_vencer_180 numeric,
  mto_por_vencer_360 numeric,
  mto_por_vencer_mas_360 numeric,
  mto_prorrogado numeric,
  mto_saneado numeric,
  mto_vencido_015 numeric,
  mto_vencido_030 numeric,
  mto_vencido_060 numeric,
  mto_vencido_090 numeric,
  mto_vencido_120 numeric,
  mto_vencido_180 numeric,
  mto_vencido_360 numeric,
  mto_vencido_mas_360 numeric,
  observaciones text,
  otras_comisiones_por_cobrar numeric,
  provision numeric,
  saldo numeric,
  tasa numeric,
  tasa_costo_efectiva numeric,
  tasa_contrato numeric,
  tipo_cambio_oficial numeric,
  id_sector_economico int,
  id_met_atencion int,
  id_tipo_zona int,
  fecha_ultima_prorroga timestamp without time zone,
  plazo_prorroga int,
  fecha_estado timestamp without time zone,
  id_estado_credito int,
  cta_contable character varying,
  id_moneda_linea int,
  mto_en_mora numeric,
  id_credito_grupo int,
  id_analista character varying
);

