CREATE TABLE icc_credito (
    legacy_cartera_id NUMERIC(10,0) PRIMARY KEY NOT NULL,
    c_period_id NUMERIC(10,0),
    cantidad_cuotas INT,
    cantidad_prorrogas INT,
    comision_acumulada_por_cobrar NUMERIC,
    cuotas_vencidas INT,
    dias_mora_interes INT,
    dias_mora_principal INT,
    fecha_otorgamiento TIMESTAMP WITHOUT TIME ZONE,
    fecha_vencimiento_credito TIMESTAMP WITHOUT TIME ZONE,
    id_clasificacion_credito INT,
    id_tipo_credito INT,
    id_credito INT,
    id_credito_anterior INT,
    id_destino_credito INT,
    id_garantia INT,
    id_linea INT,
    id_modalidad_credito INT,
    id_moneda INT,
    id_municipio INT,
    id_oficina INT,
    id_origen_recursos INT,
    id_periodo_cobro_interes INT,
    id_periodo_cobro_principal INT,
    id_sindicado INT,
    id_situacion_credito INT,
    id_tipo_agrupacion_credito INT,
    interes_corriente NUMERIC,
    interes_vencidos NUMERIC,
    mto_adjudicacion_credito NUMERIC,
    mto_intereses_por_vencer_030 NUMERIC,
    mto_intereses_por_vencer_060 NUMERIC,
    mto_intereses_por_vencer_090 NUMERIC,
    mto_intereses_por_vencer_120 NUMERIC,
    mto_intereses_por_vencer_180 NUMERIC,
    mto_intereses_por_vencer_360 NUMERIC,
    mto_intereses_por_vencer_mas_360 NUMERIC,
    mto_original NUMERIC,
    mto_por_vencer_030 NUMERIC,
    mto_por_vencer_060 NUMERIC,
    mto_por_vencer_090 NUMERIC,
    mto_por_vencer_120 NUMERIC,
    mto_por_vencer_180 NUMERIC,
    mto_por_vencer_360 NUMERIC,
    mto_por_vencer_mas_360 NUMERIC,
    mto_prorrogado NUMERIC,
    mto_saneado NUMERIC,
    mto_vencido_015 NUMERIC,
    mto_vencido_030 NUMERIC,
    mto_vencido_060 NUMERIC,
    mto_vencido_090 NUMERIC,
    mto_vencido_120 NUMERIC,
    mto_vencido_180 NUMERIC,
    mto_vencido_360 NUMERIC,
    mto_vencido_mas_360 NUMERIC,
    observaciones TEXT,
    otras_comisiones_por_cobrar NUMERIC,
    provision NUMERIC,
    saldo NUMERIC,
    tasa NUMERIC,
    tasa_costo_efectiva NUMERIC,
    tasa_contrato NUMERIC,
    tipo_cambio_oficial NUMERIC,
    id_sector_economico INT,
    id_met_atencion INT,
    id_tipo_zona INT,
    fecha_ultima_prorroga TIMESTAMP WITHOUT TIME ZONE,
    plazo_prorroga INT,
    fecha_estado TIMESTAMP WITHOUT TIME ZONE,
    id_estado_credito INT,
    cta_contable CHARACTER VARYING,
    id_moneda_linea INT,
    mto_en_mora NUMERIC,
    id_credito_grupo INT,
    id_analista INT
);